# Generated by Django 3.2.6 on 2021-08-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20210821_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cpf',
            field=models.IntegerField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
