# Generated by Django 3.2.6 on 2021-08-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_auto_20210821_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='estado_civil',
            field=models.CharField(choices=[('sol', 'Solteiro'), ('cas', 'Casado'), ('div', 'Divorciado'), ('viu', 'Viuvo')], default='cas', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino')], max_length=1, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
    ]
