# Generated by Django 3.2.6 on 2021-08-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_auto_20210821_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='organ_donor',
            field=models.BooleanField(default='True', verbose_name='doador de órgãos'),
            preserve_default=False,
        ),
    ]
