# Generated by Django 3.2.6 on 2021-08-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_client_organ_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='observation',
            field=models.TextField(default='none', max_length=500, verbose_name='observações'),
            preserve_default=False,
        ),
    ]
