# Generated by Django 3.2.6 on 2021-08-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_client_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='picture',
            field=models.ImageField(default='none', upload_to='', verbose_name='foto'),
            preserve_default=False,
        ),
    ]
