# Generated by Django 3.2.6 on 2021-08-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200, verbose_name='Modelo')),
                ('plate', models.CharField(max_length=7, verbose_name='Placa')),
                ('year', models.CharField(max_length=4, verbose_name='Ano')),
            ],
        ),
    ]
