# Generated by Django 3.2.6 on 2021-08-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_remove_car_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='plate',
            field=models.CharField(default='MKC1243', max_length=7, unique=True, verbose_name='Placa'),
            preserve_default=False,
        ),
    ]
