# Generated by Django 3.2.6 on 2021-08-22 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_car_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.car', verbose_name='Carro')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.client', verbose_name='Cliente')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.instructor', verbose_name='Instrutor')),
            ],
        ),
    ]
